name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an enhancement! Please provide details below.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the feature request
      placeholder: "What feature would you like to see?"
    validations:
      required: true
  
  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: How would this feature be used?
      placeholder: "Describe the use case and benefits"
    validations:
      required: true
  
  - type: textarea
    id: mockup
    attributes:
      label: Mockup/Example
      description: Add mockups, screenshots, or examples if applicable
